AutoGarage/Controllers/AutomoveisController.cs
using AutoGarage.Data;
using AutoGarage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace AutoGarage.Controllers
{
    public class AutomoveisController : Controller
    {
        private readonly AutoGarageContext _context;

        public AutomoveisController(AutoGarageContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            
            var automoveis = _context.Automoveis.Include(a => a.Cliente).ToList();

           
            return View(automoveis);
        }


        ////////////////////////////////////////////////////////////////////////////////
        /////Adicionar

        [HttpGet]
        public IActionResult AdicionarRegisto(int? ClienteId)
        {
            
            
            var automovel = new AutomoveisModel
            {   
                ClienteId = ClienteId
            };

            return View(automovel);
        }

        [HttpPost]
        public IActionResult AdicionarRegisto(AutomoveisModel automovel)
        {
            if (ModelState.IsValid)
            {
                 
                _context.Automoveis.Add(automovel);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        ////////////////////////////////////////////////////////////////
        /////////////////Editar

        [HttpGet]
        public IActionResult EditarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            AutomoveisModel automovel = _context.Automoveis.FirstOrDefault(automovel => automovel.Id == id);

            if (automovel == null)
            {
                return NotFound();
            }

            return View(automovel);
        }
        [HttpPost]
        public IActionResult EditarRegisto(AutomoveisModel automovel)
        {
            if (ModelState.IsValid)
            {
                _context.Automoveis.Update(automovel);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(automovel);
        }
        //////////////////////////////////////////////////////////////////////////
        //////////////////////////////////Remover
        [HttpGet]
        public IActionResult EliminarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            AutomoveisModel automovel = _context.Automoveis.FirstOrDefault(auto => auto.Id == id);

            if (automovel == null)
            {
                return NotFound();
            }

            return View(automovel);
        }
        [HttpPost]
        public IActionResult EliminarRegisto(AutomoveisModel automovel)
        {
            if (automovel == null)
            {
                return NotFound();
            }
            _context.Automoveis.Remove(automovel);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        //////////////////////////////////////////////////////////
        /////////////////////////Detalhes
        public IActionResult Detalhes(int id)
        {
            var automovel = _context.Automoveis
                .Include(c => c.Servicos)
                .Include(a => a.Cliente)
                .FirstOrDefault(c => c.Id == id);

            if (automovel == null)
            {
                return NotFound();
            }

            return View(automovel);
        }

    }
}

AutoGarage/Controllers/ClientesController.cs
using AutoGarage.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using AutoGarage.Models;
using Microsoft.EntityFrameworkCore;

namespace AutoGarage.Controllers
{
    public class ClientesController : Controller
    {
        private readonly AutoGarageContext _context;

        public ClientesController(AutoGarageContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // vai buscar os dados da tabela de clientes
            var clientes = _context.Clientes.ToList();

            // Passa os dados para a view
            return View(clientes);
        }

        ////////////////////////////////////////////
        /////Adicionar

        [HttpGet]
        public IActionResult AdicionarRegisto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdicionarRegisto(ClientesModel cliente)
        {
            if(ModelState.IsValid){ 
                _context.Clientes.Add(cliente);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        ///////////////////////////////////////////////////////////////////
        /////////////////Editar
        
        [HttpGet]
        public IActionResult EditarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ClientesModel cliente = _context.Clientes.FirstOrDefault(cliente => cliente.Id == id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }
        [HttpPost]
        public IActionResult EditarRegisto(ClientesModel cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Clientes.Update(cliente);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(cliente);
        }
        //////////////////////////////////////////////////////////////////////////
        //////////////////////////////////Remover
        [HttpGet]
        public IActionResult EliminarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ClientesModel cliente = _context.Clientes.FirstOrDefault(cliente => cliente.Id == id);

            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }
        [HttpPost]
        public IActionResult EliminarRegisto(ClientesModel cliente)
        {
            if (cliente == null)
            {
                return NotFound();
            }
            _context.Clientes.Remove(cliente);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        //////////////////////////////////////////////////////////
        /////////////////////////Detalhes
        public IActionResult Detalhes(int id)
        {
            var cliente = _context.Clientes
                .Include(c => c.Automoveis) 
                .FirstOrDefault(c => c.Id == id);

            if (cliente == null)
            {
                return NotFound(); 
            }

            return View(cliente);
        }

    }
}

AutoGarage/Controllers/ServicosController.cs
using AutoGarage.Data;
using AutoGarage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace AutoGarage.Controllers
{
    public class ServicosController : Controller
    {
        private readonly AutoGarageContext _context;

        public ServicosController(AutoGarageContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // vai buscar os dados da tabela de automoveis
            var servicos = _context.Servicos.Include(a => a.Automovel).ToList();

            // Passa os dados para a view
            return View(servicos);
        }
        ////////////////////////////////////////////////////////////////////////////////
        /////Adicionar

        [HttpGet]
        public IActionResult AdicionarRegisto(int AutomovelId)
        {
           
            var servico = new ServicosModel
            {
                AutomovelId = AutomovelId,
            };

            return View(servico);
        }

        [HttpPost]
        public IActionResult AdicionarRegisto(ServicosModel servico)
        {
            if (ModelState.IsValid)
            {

                _context.Servicos.Add(servico);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        //////////////////////////////////////////////////////////////////////////////////
        ////////////////////Editar

        [HttpGet]
        public IActionResult EditarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ServicosModel servico = _context.Servicos.FirstOrDefault(servico => servico.Id == id);

            if (servico == null)
            {
                return NotFound();
            }

            return View(servico);
        }
        [HttpPost]
        public IActionResult EditarRegisto(ServicosModel servico)
        {
            if (ModelState.IsValid)
            {
                _context.Servicos.Update(servico);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(servico);
        }
        ///////////////////////////////////////////////////////////////////
        //////////////////////////////////Remover
        [HttpGet]
        public IActionResult EliminarRegisto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ServicosModel servicos = _context.Servicos.FirstOrDefault(serv => serv.Id == id);

            if (servicos == null)
            {
                return NotFound();
            }

            return View(servicos);
        }
        [HttpPost]
        public IActionResult EliminarRegisto(ServicosModel servicos)
        {
            if (servicos == null)
            {
                return NotFound();
            }
            _context.Servicos.Remove(servicos);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AutoGarage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoGarage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/slate.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoGarage.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
    <header class="z-3">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark text-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">AutoGarage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Automoveis" asp-action="Index">Automóveis</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Servicos" asp-action="Index">Serviços</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sobre" asp-action="Index">Sobre este projeto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-lg-2">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top fixed-bottom text-muted bg-dark text-white ">
        <div class="container p-lg-2">
            &copy; 2023 - AutoGarage - João Lapas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>